In [ ]:
!pip install pillow mnist numpy sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from PIL import Image
import mnist
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix


In [ ]:
# training 
x_train = mnist.train_images()
y_train = mnist.train_labels()


In [ ]:
#testing
x_test = mnist.test_images()
y_test = mnist.test_labels()



In [ ]:
print("X _TRAIN = ", x_train)
print("X _ TEST = ", x_test)
print("Y _TRAIN = ", y_train)
print("y _ TEST = ", y_test)

X _TRAIN =  [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
X _ TEST =  [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0

In [ ]:
print(x_train.ndim)

3


In [ ]:
print(x_test.ndim)
print(x_test.shape)

3
(10000, 28, 28)


In [ ]:
x_train = x_train.reshape((-1,28*28))
x_test = x_test.reshape((-1,28*28))

In [ ]:
print(x_train[5])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0  13  25 100 122   7   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0  33 151 208 252 252 252 146   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0  40 152 244 252 253 224 211 252 232
  40   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  15
 152 239 252 252 252 216  31  37 252 252  60   0   

In [ ]:
x_train = (x_train/256)
x_test = (x_test/256)

In [ ]:
print(x_train[0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [ ]:
model = MLPClassifier(solver = 'adam',activation = 'relu',hidden_layer_sizes =(64,64))

In [ ]:
model.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(64, 64))

In [ ]:
predictions =model.predict(x_test)


In [ ]:
accuracy = confusion_matrix(y_test,predictions)

In [ ]:
print(accuracy)

[[ 970    1    1    0    1    0    2    1    2    2]
 [   0 1124    1    2    1    1    2    1    3    0]
 [   2    2 1011    2    2    0    2    3    7    1]
 [   0    0    5  986    0    5    0    4    5    5]
 [   1    0    6    0  952    1    4    5    1   12]
 [   1    0    0    8    0  870    3    3    4    3]
 [   3    3    3    1    1    7  940    0    0    0]
 [   0    6   11    4    1    0    0  997    3    6]
 [   3    1    2    4    3    4    1    3  949    4]
 [   1    4    0    6    6    2    1    3    1  985]]


In [ ]:
def accura(cm):
  diagonal = cm.trace()
  elements = cm.sum()
  return diagonal/elements

In [ ]:
print(accura(accuracy))

0.9784
